version: "3.9"

services:
  gateway:
    build:
      context: apps/gateway
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - SOCKET_EVENT_SECRET=wTD0y:6Ch(Z|H[Xh<rp"1Gx)3J]N[c
      - REDIS_HOST=redis
      - REDIS_PASSWORD=9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
      - REDIS_PORT=6379
      - SALTED_PASSWORD=10
      - ACCESS_TOKEN_SECRET=XtitPOagxC
      - ACCESS_TOKEN_LIFE=1h
      - REFRESH_TOKEN_SECRET=grvtq3QvYU
      - REFRESH_TOKEN_LIFE=2592000
      - PASSWORD_LIFE=600
      - REFRESH_TOKEN_LIFE_D=30d
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo
      - GITHUB_CLIENT_ID=Iv1.98f469e0d7ac7fd6
      - GITHUB_CLIENT_SECRET=c39a56aa94bb5a2eb788fc17ece6be6422c42cf9
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis
    command: redis-server --requirepass 9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  notifications:
    build:
      context: apps/notifications
      dockerfile: Dockerfile
      target: production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - GATEWAY_PORT=3000
      - SOCKET_EVENT_SECRET=wTD0y:6Ch(Z|H[Xh<rp"1Gx)3J]N[c
      - REDIS_HOST=redis
      - REDIS_PASSWORD=9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
      - REDIS_PORT=6379
      - CLIENT_BASE_URL=https://queueoverflow.online
      - GMAIL_USER=4rumservice@gmail.com
      - GMAIL_PASSWORD=stanuozjbzxtlfrl
      - PGHOST=postgres
      - PGDATABASE=default
      - PGUSER=default
      - PGPASSWORD=9yEumx4mEb
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo
    depends_on:
      - redis
      - postgres

  users:
    build:
      context: apps/users
      dockerfile: Dockerfile
      target: production
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PASSWORD=9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
      - REDIS_PORT=6379
      - SALTED_PASSWORD=10
      - PGHOST=postgres
      - PGDATABASE=default
      - PGUSER=default
      - PGPASSWORD=9yEumx4mEb
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo
    depends_on:
      - redis
      - postgres

  cms:
    build:
      context: apps/cms
      dockerfile: Dockerfile
      target: production
    ports:
      - "3003:3003"
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=3003
      - REDIS_HOST=redis
      - REDIS_PASSWORD=9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGDATABASE=default
      - PGUSER=default
      - PGPASSWORD=9yEumx4mEb
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo

  posts:
    build:
      context: apps/posts
      dockerfile: Dockerfile
      target: production
    ports:
      - "3004:3004"
    depends_on:
      - redis
      - postgres
    environment:
      - NODE_ENV=production
      - PORT=3004
      - REDIS_HOST=redis
      - REDIS_PASSWORD=9QYVMZNxuSmPp1GyvNs38FKh4rqBMZfCMrCWkXlnmpSm
      - REDIS_PORT=6379
      - RECOMMENDATIONS_HOST=http://recommendations:8000
      - PGHOST=postgres
      - PGDATABASE=default
      - PGUSER=default
      - PGPASSWORD=9yEumx4mEb
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo

  elasticsearch:
    image: elasticsearch:8.10.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_PASSWORD=Y3KgattXgebGXUd
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - queueoverflow

  search:
    build:
      context: apps/search
      dockerfile: Dockerfile
      target: production
    depends_on:
      - redis
      - elasticsearch
      - postgres
    networks:
      - queueoverflow
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=Y3KgattXgebGXUd
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo
    
  recommendations:
    build:
      context: apps/recommendations
    ports:
      - "8000:3006"
    environment:
      - DATABASE_URL=postgresql://default:9yEumx4mEb@postgres/default
      - RABBITMQ_URL=amqps://pkeilyyo:nfbO7ZksScLaUj47ml4lPp3upf2fLHtN@octopus.rmq3.cloudamqp.com/pkeilyyo

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: default
      POSTGRES_PASSWORD: 9yEumx4mEb
      POSTGRES_DB: default

networks:
  queueoverflow:
    name: queueoverflow
    external: true
    driver: bridge